### ISSUE TITLE
hive-metastore failing to spin up.

### ISSUE THREAD

**Issue by ramkrishnakadam** [Thelin90/datapains-trino-k8s#2]
Hello,

i am stuck on later part where "hive-metastore" fail to load.

<img width="525" alt="2024-09-05_14-48-29" src="https://github.com/user-attachments/assets/6d37197c-bf86-4bd7-baf8-08e7352f1a9f">

<img width="1600" alt="2024-09-05_14-50-57" src="https://github.com/user-attachments/assets/8c8fc3c7-a9c4-467a-888b-9b9d55cbeeb1">

Is there anything I need to change in YMAL file. I am in repo this time.

**Comment by Thelin90** [comment]
Hello.

`Nothing needs to be changed or altered, in any way, this is all tested before being published`.

First of all, where are you running this? The setup is for local, hence `local/`.

https://github.com/Thelin90/datapains-trino-k8s/blob/main/tools/k8s/vanilla/local/metastore/06-hive-sts.yml#L24

If you use `docker-desktop` k8s, then this has to be set to `Never`, when running locally.

This means you have to have built the image first.

Are you sure the image exists?

```bash
docker images
```

Also it is important you do not change this policy, if you have, it has to be `Never`.

You should see

<img width="1374" alt="image" src="https://github.com/user-attachments/assets/ae4ae92d-e38c-46ad-9548-9fc86c3a02d4">

If you use this in a real cluster, it should be `for example`:

`IfNotPresent`, or `Always`.

But since this is a local setup it is set to `Never`.

So if you are trying to take this into a real cluster it won't work since the image does not exist on public dockerhub.


If you are running this in kind, or minikube, I can't help you unfortunately since the setup is made for `docker-desktop -> k8s`.

I just ran exactly as of the main branch, and this works for me, so it works for me given:

* using docker desktop with k8s enabled
* build metastore image first
* run apply components for metastore

<img width="606" alt="image" src="https://github.com/user-attachments/assets/eb600dc1-3048-403c-a7ae-3f4d074c81d4">

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/47203cc8-eed9-4714-8d3d-6c7b37537a33">

You should see

`Container image "datapains/metastore:0.0.1" already present on machine`

This indicates the image actually exists.

Take the time and read the README very carefully before you post issues. And also try a bit more yourself, given your previous issue. 

I am being very generous with my responses here given you do not provide any context to what you have tried and not tried. If you keep posting issues like this, I will simply not answer them. You must provide context, for ex:

* I ran this, I followed readme instructing X
* I can see image exists, I run apply still get error etc.

It feels like you are just posting an issue without debugging to why this happens yourself.

If you don't have experience in docker and k8s itself, please do some research around these topics. This setup requires some form of very basic docker knowledge.

Closing this issue since there is nothing wrong with this setup, if you have issues from this. And if you don't provide exact steps what you have done, looked into, it will just be ignored.
